{
 "title": "Openstack Health",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cloud",
    "label": "Cloud",
    "query": "label_values(openstack_api_response_seconds, cloud_name)"
   }
  ]
 },
 "panels": [
  { "title": "SLAs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "content": "\n# SLAs\nSLAs are calculated on a monthly basis.\n\n1. 99% Openstack API Uptime\n2. 99% Openstack API non 5xx backend errors\n3. Average API Response Time under 8 Seconds\n4. 99.99% VM uptime\n\nSee the below chart for details on how much downtime each percentage equals.\n\n| Percentage | Yearly         | Monthly           | Weekly |\n|:-------------:|:-------------:|:-------------:|:-------------:|\n|99%|3.65 days| 7.2 hours| 1.68 hours|\n|99.5%|1.83 days|3.6 hours|50.4 minutes|\n|99.9%|8.76 hours|43.2 minutes|10.1 minutes|\n|99.95%|4.38 hours|21.56 minutes|5.04 minutes|\n|99.99%|52.56 minutes|4.32 minutes|1.01 minutes|\n\n\n\n"
  },
  {
   "title": "Nova API Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(avg_over_time(openstack_api_status{api_name=\"nova\",cloud_name=\"$cloud\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Neutron API Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "avg(avg_over_time(openstack_api_status{api_name=\"neutron\", cloud_name=\"$cloud\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Cinder API Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "avg(avg_over_time(openstack_api_status{api_name=\"cinder\", cloud_name=\"$cloud\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Horizon API Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "avg(avg_over_time(openstack_horizon_status{cloud_name=\"$cloud\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Nova API Avg Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_api_response_seconds{api_name=\"nova\", cloud_name=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Neutron API Avg Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_api_response_seconds{api_name=\"neutron\", cloud_name=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Cinder API Avg Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_api_response_seconds{api_name=\"cinder\", cloud_name=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Horizon API Avg Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_api_response_seconds{exported_job=\"openstack_horizon_api\", app=\"horizon\", cloud=\"$cloud\"}"
    }
   ]
  },
  { "title": "Current Cloud Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 21 },
   "content": "\n# Current Status\n\nAPIs marked as \"Good\" and in green have a current 10 minute average response time of below 5 seconds. \n\nAPIs marked as \"Degraded\" and in orange have a current 10 minute average response time of above 5 seconds and below 8 seconds.\n\nAPIs marked as \"Unusable\" and in red have a current 10 minute average response time above 8 seconds.\n\n\n"
  },
  {
   "title": "Horizon Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(openstack_horizon_response_seconds{cloud_name=\"$cloud\"}[10m])"
    }
   ]
  },
  {
   "title": "Nova API Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(openstack_api_response_seconds{api_name=\"nova\", cloud_name=\"$cloud\"}[10m])"
    }
   ]
  },
  {
   "title": "Neutron API Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(openstack_api_response_seconds{api_name=\"neutron\", cloud_name=\"$cloud\"}[10m])"
    }
   ]
  },
  {
   "title": "Cinder API Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(openstack_api_response_seconds{api_name=\"cinder\", cloud_name=\"$cloud\"}[10m])"
    }
   ]
  },
  {
   "title": "Horizon Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_horizon_status{cloud_name=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Nova Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_api_status{api_name=\"nova\", cloud_name=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Neutron Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_api_status{api_name=\"neutron\", cloud_name=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Cinder Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_api_status{api_name=\"cinder\", cloud_name=\"$cloud\"}"
    }
   ]
  },
  { "title": "Status Timelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Nova Status TImeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_api_status{api_name=\"nova\", cloud_name=\"$cloud\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Neutron Status TImeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_api_status{api_name=\"neutron\", cloud_name=\"$cloud\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Cinder Status TImeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_api_status{api_name=\"cinder\", cloud_name=\"$cloud\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Horizon Status TImeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_horizon_status{cloud_name=\"$cloud\"}",
     "legendFormat": "horizon"
    }
   ]
  },
  { "title": "Response Time Timelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Nova Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_api_response_seconds{api_name=\"nova\", cloud_name=\"$cloud\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Neutron Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_api_response_seconds{api_name=\"neutron\", cloud_name=\"$cloud\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Cinder Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_api_response_seconds{api_name=\"cinder\", cloud_name=\"$cloud\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Horizon HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " openstack_horizon_response_seconds{cloud_name=\"$cloud\"}",
     "legendFormat": "horizon"
    }
   ]
  },
  { "title": "Compute Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Instance Deploy Seconds to Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_instance_deploy_seconds_to_ping{cloud_name=\"$cloud\"}",
     "legendFormat": "{{ hypervisor_hostname}}"
    }
   ]
  }
 ]
}