{
 "title": "Openstack Hypervisors",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloud",
    "label": "Cloud",
    "query": "label_values(openstack_hypervisor_used_ram_mb, cloud_name)"
   },
   {
    "name": "hypervisor",
    "label": "Hypervisor",
    "query": "label_values(openstack_hypervisor_used_ram_mb{cloud_name=~\"$cloud\"}, hypervisor_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "openstack_hypervisor_used_ram_mb{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"} / openstack_hypervisor_total_ram_mb{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}"
    }
   ]
  },
  {
   "title": "VCPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "openstack_hypervisor_used_cpus{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"} / openstack_hypervisor_total_cpus{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}"
    }
   ]
  },
  {
   "title": "Local Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "openstack_hypervisor_local_gb_used{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"} / openstack_hypervisor_local_gb_total{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_hypervisor_enabled{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}"
    }
   ]
  },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_hypervisor_up{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_hypervisor_running_vms{cloud_name=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}",
     "legendFormat": "VMs"
    }
   ]
  }
 ]
}